"""Build the site bundle for the Asunción 2021→2026 section.

Reads the committed extraction (`data/asuncion_2026/asuncion.json`) and writes
`site/assets/asuncion-data.js`, which exposes the global `window.ASUNCION` used
by `site/assets/asuncion.js`. Mirrors the role of `make_choropleth.py` (which
emits `site/assets/data.js`).

Run: `uv run python make_asuncion.py`
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "data" / "asuncion_2026" / "asuncion.json"
GEO = ROOT / "data" / "asuncion_2026" / "asuncion_geo.json"
RAW = ROOT / "data" / "raw_results.json"
DST = ROOT / "site" / "assets" / "asuncion-data.js"


def asuncion_2026() -> dict | None:
    """The real 2026 TSJE result for the Capital, from our national dataset.

    Used to (a) show the elected intendente and the 2026 candidate breakdown and
    (b) fill the PDC 2026 share the Power BI model left blank.
    """
    if not RAW.exists():
        return None
    for rec in json.loads(RAW.read_text(encoding="utf-8"))["records"]:
        if rec.get("distrito_name", "").upper() == "ASUNCION":
            t = rec.get("totales", {})
            total = t.get("totalVotos") or 0
            cands = [
                {"lista": c.get("numLista"), "nombre": c.get("nomCandidato"),
                 "partido": c.get("desPartido"), "votos": c.get("votos"),
                 "color": c.get("colLista"),
                 "pct": (c.get("votos") or 0) / total if total else None}
                for c in rec.get("candidatos", [])
            ]
            return {
                "winner": rec.get("winner"),
                "candidatos": cands,
                "totalVotos": total,
                "blancos": t.get("blancos"),
                "nulos": t.get("nulos"),
                "canElectores": t.get("canElectores"),
                "mesas": t.get("totalMesas"),
            }
    return None


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    if GEO.exists():
        data["geo"] = json.loads(GEO.read_text(encoding="utf-8"))

    r26 = asuncion_2026()
    if r26:
        data["resultado2026"] = r26
        # fill the PDC 2026 share the model left blank, from the real TSJE data
        for c in r26["candidatos"]:
            if "DEMOCRATA CRISTIANO" in (c["partido"] or "").upper() and c.get("pct"):
                for f in data["fuerzas"]:
                    if f["sigla"] == "PDC" and f.get("p26") is None:
                        f["p26"] = round(c["pct"], 6)

    n = len(data["barrios"])
    m = len(data["locales"])
    v = data["correlacion"]["vars"]
    geo_n = len(data.get("geo", {}).get("barrios", []))
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    DST.write_text(
        "/* Generated by make_asuncion.py — do not edit.\n"
        "   Source: data/asuncion_2026/asuncion.json + barrios_geo.json (OSM) + raw_results.json (2026). */\n"
        f"window.ASUNCION = {payload};\n",
        encoding="utf-8",
    )
    print(f"[ok] {DST.relative_to(ROOT)}  ({DST.stat().st_size:,} bytes)")
    print(f"     barrios={n} locales={m} zonas={len(data['zonas'])} vars={len(v)} geo_features={geo_n}")
    print(f"     2026: {'ok' if r26 else 'missing'}")


if __name__ == "__main__":
    main()
