"""Build the site bundle for the Asunción 2021→2026 section.

Reads the committed extraction (`data/asuncion_2026/asuncion.json`) and writes
`site/assets/asuncion-data.js`, which exposes the global `window.ASUNCION` used
by `site/assets/asuncion.js`. Mirrors the role of `make_choropleth.py` (which
emits `site/assets/data.js`).

Run: `uv run python make_asuncion.py`
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "data" / "asuncion_2026" / "asuncion.json"
DST = ROOT / "site" / "assets" / "asuncion-data.js"


def main() -> None:
    data = json.loads(SRC.read_text(encoding="utf-8"))
    n = len(data["barrios"])
    m = len(data["locales"])
    v = data["correlacion"]["vars"]
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    DST.write_text(
        "/* Generated by make_asuncion.py — do not edit.\n"
        "   Source: data/asuncion_2026/asuncion.json (Asunción 2021→2026, Power BI public report). */\n"
        f"window.ASUNCION = {payload};\n",
        encoding="utf-8",
    )
    print(f"[ok] {DST.relative_to(ROOT)}  ({DST.stat().st_size:,} bytes)")
    print(f"     barrios={n} locales={m} zonas={len(data['zonas'])} vars={len(v)}")


if __name__ == "__main__":
    main()
